Alpha version release
AdTechMedia/drupal-module pull request #22
Opened 2016-10-25 14:01 UTC by eistrati

2016-11-03 06:47 UTC, AlexanderC requested changes
Please check out and fix the issues pointed to.

2016-11-03 06:47 UTC, AlexanderC commented on src/AtmClient.php
> +              'relatedVideoCb' => "function(onReady) { onReady({ 'iPad,iPhone,Apple': ['https://www.youtube.com/watch?v=OzQh6wDb2oE&t=23s'] }) }",
The `onReady` call should look like this: `onReady('https://www.youtube.com/watch?v=OzQh6wDb2oE&t=23s')`

2016-11-03 06:47 UTC, AlexanderC commented on src/AtmClient.php
> +      $request = $client->get('https://demo.adtechmedia.io/atm-admin/atm-build/templates.json');
Please move the endpoint to config

2016-11-03 06:47 UTC, AlexanderC commented on src/Form/AdTechMediaConfigForm.php
> +      '#options' => [
Please use the `/atm-admin/property/supported-countries` endpoint to fetch such data from

2016-11-03 06:47 UTC, AlexanderC commented on src/Form/AdTechMediaConfigForm.php
> +      '#options' => [
Please set it up depending on chosen country (@see `/atm-admin/property/supported-countries`)

2016-11-10 19:41 UTC, eistrati commented
Please fix the problems pointed out by @AlexanderC

2016-11-10 19:41 UTC, closed without merging