Building the module from scratch
AdTechMedia/drupal-module pull request #37
Opened 2017-01-31 23:43 UTC by eistrati

2017-02-20 07:54 UTC, AlexanderC requested changes
Please fix the issues found

2017-02-20 07:54 UTC, AlexanderC commented on atm.libraries.yml
> +    https://adm.adtechmedia.io/atm-core/atm-build/atmTpl.js:  { type: external }
Please change it to `https://api.adtechmedia.io/atm-core/atm-build/atmTpl.js`

2017-02-20 07:54 UTC, AlexanderC commented on config/install/atm.settings.yml
> +base_url: https://api.adtechmedia.io/prod
Please change it to `https://api.adtechmedia.io/v1`

2017-02-20 07:54 UTC, AlexanderC commented on src/AtmHttpClient.php
> +    $client = new Client();
Could we cache `Client` instance to reuse it for all requests?

2017-02-20 07:54 UTC, AlexanderC commented on src/AtmHttpClient.php
> +  public function getPropertySupportedCountries() {
Why not using `sendRequest(...)`?

2017-02-20 07:54 UTC, AlexanderC commented on src/AtmHttpClient.php
> +    $client = new Client();
Why not using `sendRequest(...)`?

2017-02-20 07:54 UTC, AlexanderC commented on src/AtmHttpClient.php
> +        $file_system->mkdir($path, 0777, TRUE);
Please change permissions to `0644`? (@see http://permissions-calculator.org/decode/0644/)

2017-02-27 14:31 UTC, AlexanderC requested changes

2017-02-27 14:31 UTC, AlexanderC commented on js/admin.js
> +            '<iframe src="https://www.adtechmedia.io/terms/dialog.html" frameborder="0"></iframe>' +
Please load terms using an ajax call and inserting the content into the modal rather than rendering an iframe

2017-02-27 14:31 UTC, AlexanderC commented on atm.libraries.yml
> +    https://adm.adtechmedia.io/atm-core/atm-build/atmTpl.js:  { type: external }
Please change it to https://api.adtechmedia.io/atm-core/atm-build/atmTpl.js

2017-03-02 00:15 UTC, azzaromax commented on src/AtmHttpClient.php
> +    $client = new Client();
https://github.com/AdTechMedia/drupal-module/pull/50/files#diff-9860f9ae0c7a393358b73c33b148897dR66

2017-03-02 00:15 UTC, azzaromax commented on src/AtmHttpClient.php
> +  public function getPropertySupportedCountries() {
https://github.com/AdTechMedia/drupal-module/pull/50/files#diff-9860f9ae0c7a393358b73c33b148897dR66

2017-03-02 00:15 UTC, azzaromax commented on src/AtmHttpClient.php
> +    $client = new Client();
https://github.com/AdTechMedia/drupal-module/pull/50/files#diff-9860f9ae0c7a393358b73c33b148897dR66

2017-03-02 00:16 UTC, azzaromax commented on js/admin.js
> +            '<iframe src="https://www.adtechmedia.io/terms/dialog.html" frameborder="0"></iframe>' +
https://github.com/AdTechMedia/drupal-module/pull/50/files#diff-a0623ef93657e56554c5ddda522ed690R154

2017-03-02 00:17 UTC, azzaromax commented on atm.libraries.yml
> +    https://adm.adtechmedia.io/atm-core/atm-build/atmTpl.js:  { type: external }
https://github.com/AdTechMedia/drupal-module/pull/50/files#diff-38491bef7331dc1e9a7fad19520941c0R13

2017-03-03 14:18 UTC, AlexanderC approved these changes

2017-03-03 14:19 UTC, merged