Preparing the alpha release
AdTechMedia/drupal-module pull request #85
Opened 2017-04-08 14:01 UTC by eistrati

2017-06-13 14:38 UTC, AlexanderC requested changes

2017-06-13 14:38 UTC, AlexanderC commented on atm.module
> +  if (REQUEST_TIME - \Drupal::state()->get('google_atm.last_cache') >= 86400) {
Is there a reason the state is prefixed `google_atm` and not just `atm`?

2017-06-13 14:38 UTC, AlexanderC commented on atm.module
> +  if (REQUEST_TIME - \Drupal::state()->get('google_atm.last_cache') >= 86400) {
Please move `86400` ttl value to config

2017-06-13 14:38 UTC, AlexanderC commented on atm.module
> +  if (REQUEST_TIME - \Drupal::state()->get('google_atm.last_cache') >= 86400) {
What's the difference between 'google_atm.last_cache' and `atm.last_cache`?

2017-06-13 14:38 UTC, AlexanderC commented on config/install/atm.settings.yml
>  register_url: https://www.adtechmedia.io/admin/accounts/signup
Please create an `atm.settings.dev.yml` and load it with all development endpoints when localhost used

2017-06-13 14:38 UTC, AlexanderC commented on src/Controller/AtmApiController.php
> +
Please handle the exception properly

2017-06-13 14:38 UTC, AlexanderC commented on src/Helper/AtmApiHelper.php
>      $script = gzdecode($script);
What happens if the script is not gziped?

2017-06-13 14:38 UTC, AlexanderC commented on src/Helper/AtmApiHelper.php
> +    return "
Could we move css to static assets?

2017-06-16 11:39 UTC, azzaromax commented on atm.module
> +  if (REQUEST_TIME - \Drupal::state()->get('google_atm.last_cache') >= 86400) {
Need rename `google_atm.last_cache` to `atm.last_cache`
My error

2017-06-16 11:41 UTC, azzaromax commented on config/install/atm.settings.yml
>  register_url: https://www.adtechmedia.io/admin/accounts/signup
It's impossible
Drupal load config/install/atm.settings.yml by pattern "{module_name}.settings.yml"

2017-06-16 11:43 UTC, azzaromax commented on src/Controller/AtmApiController.php
> +
Ok, I can write exception to log

2017-06-16 11:45 UTC, azzaromax commented on src/Helper/AtmApiHelper.php
> +    return "
And what's the point? This css contains a template and not a full css

2017-10-04 14:44 UTC, merged